### ISSUE TITLE
Small borders around feature image

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/saga#3]
When I browse on WIN 8 and Chrome I see small white borders around feature images. Is this intentional? Or just a chrome bug.

![saga_image](https://cloud.githubusercontent.com/assets/1820415/4116343/f94cc7e2-3283-11e4-8a33-ed53e0b4903b.jpg)

**Comment by justintadlock** [comment]
I'm not getting any borders on Windows 8 + Chrome.

![w8-chrome-no-border](https://cloud.githubusercontent.com/assets/1816309/4120010/3c38489e-32af-11e4-8549-0219cefc5f46.jpg)

**Comment by samikeijonen** [comment]
Okay, I'm not gonna worry about it.

**Comment by samikeijonen** [comment]
Same here, laptop screen messing with me.
