### ISSUE TITLE
Nav lines

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/saga#4]
When I change nav 3 lines font size from 21px to 19px, 3 lines looks better in my eyes because the lines have same thickness. I know it's just a small detail. I can also change it to child theme.

![nav_worse](https://cloud.githubusercontent.com/assets/1820415/4117918/71af64b4-3299-11e4-96d4-b875da773bd5.jpg)

![nav_better](https://cloud.githubusercontent.com/assets/1820415/4117919/75912e8c-3299-11e4-9fb6-d29ceec49e84.jpg)

**Comment by justintadlock** [comment]
19px looks bad for me.  What does 24px look like for you?  20px, 22px, and 23px doesn't look right for me.  24px looks good, but it's a little too big for me.

**Comment by samikeijonen** [comment]
It seems that Font Awesome base font size is 14px. But 28px would definitely look too big and 14px too small.

https://github.com/FortAwesome/Font-Awesome/issues/2882

For Genericons base size is 16px.

**Comment by justintadlock** [comment]
Yep, I know it has a base of 14px, which is why 21px should look good.  I'm testing on my iPad and laptop (W8 + Chrome), which looks OK at 21px for me.

**Comment by samikeijonen** [comment]
Does it look good when you zoom in and out? 

Anyways this is so little detail that we can live with that. But it's annoying:)

**Comment by samikeijonen** [comment]
It was my laptop screen acting weird, everything is okay now. 21px is perfect.
