### ISSUE TITLE
Mediaelement CSS in WordPress 4.1

### ISSUE THREAD

**Issue by jayj** [justintadlock/saga#6]
The CSS for Mediaelement.js has been changed in WordPress 4.1.

Mediaelement has added the `.mejs-offscreen` class (https://github.com/johndyer/mediaelement/commit/374e957cfb6b6b7255f50f844bf94a5a73b55d7f) to hide screen reader text.

It needs to be added to Saga's medialement.css, otherwise it looks like this:
![Image of Medialement in Saga](http://i.imgur.com/XJ4IY1B.png)

**Comment by justintadlock** [comment]
I'm closing this and adding the issue upstream: https://github.com/justintadlock/theme-mediaelement/issues/5
